#!/usr/bin/python

import sys
# import csv
import geocoder

# fix unicode writing errors for python 2.7
reload(sys)
sys.setdefaultencoding('utf8')

# don't use a map in order to preserve order and catch exceptions.
def geocode_latlng(address):
    APIKEY = "YOURKEY" #replace with actual mapquest key, can get for free
    # writer = csv.writer(sys.stdout)
    try:
        g = geocoder.mapquest(address, key=APIKEY)
        print("{},{},{},{},{},{},{}".format(address, g.lat, g.lng, g.city, g.county, g.state, g.country))
    except:
        try:
            g = geocoder.mapquest(address, key=APIKEY)
            # print(address + "," + g.lat + "," + g.lng + ",")
            print("{},{},{},{},{},{},{}".format(address, g.lat, g.lng, g.city, g.county, g.state, g.country ))
        except:
            print("{},{},{},{},{},{},{}".format(address, None, None, None, None, None, None))

    # writer.writerow([
    #     address,
    #     g.lat,
    #     g.lng
    # ])


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('uid required')
        sys.exit()
    address = sys.argv[1].decode(sys.getfilesystemencoding())
    geocode_latlng(address)
